added deploy task

diff --git a/tekton/pipeline.yaml b/tekton/pipeline.yaml
--- a/tekton/pipeline.yaml
+++ b/tekton/pipeline.yaml
@@ -2,6 +2,8 @@
 # This pipeline needs the following tasks from Tekton Hub
 #   - git-clone
 #   - flake8
+#   - buildah
+#   - openshift-client
 #
 ---
 apiVersion: tekton.dev/v1beta1
@@ -53,7 +55,11 @@ spec:
               pip install flake8
               cd /workspace/source
               echo "Running flake8 linting..."
-              flake8 service tests                 --count                 --max-complexity=10                 --max-line-length=127                 --statistics || echo "⚠️ flake8 failed but continuing pipeline"
+              flake8 service tests \
+                --count \
+                --max-complexity=10 \
+                --max-line-length=127 \
+                --statistics || echo "⚠️ flake8 failed but continuing pipeline"
       runAfter:
         - clone
 
@@ -75,6 +81,25 @@ spec:
         kind: ClusterTask
       params:
         - name: IMAGE
-          value: $(params.build-image)
+          value: "$(params.build-image)"
       runAfter:
         - tests
+
+    - name: deploy
+      workspaces:
+        - name: manifest-dir
+          workspace: pipeline-workspace
+      taskRef:
+        name: openshift-client
+        kind: ClusterTask
+      params:
+        - name: SCRIPT
+          value: |
+            echo "Updating manifest..."
+            sed -i "s|IMAGE_NAME_HERE|$(params.build-image)|g" deploy/deployment.yaml
+            cat deploy/deployment.yaml
+            echo "Deploying to OpenShift..."
+            oc apply -f deploy/
+            oc get pods -l app=accounts
+      runAfter:
+        - build
